title = "Pushkar Ghanekar"
baseURL = "https://www.pushkarghanekar.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "West Lafayette, IN"
email = "pghaneka@purdue.edu"
favicon = "/favicon.ico"
firstName = "Pushkar"
lastName = "Ghanekar"
phone = ""
profileImage = "img/main_image.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = true
showQr = true
showSkills = false
showBlog = false 

[params.google]

[params.google.analytics]
trackerID = "UA-167983168-1"

[[params.handles]]
link = "https://www.linkedin.com/in/pushkarghanekar/"
name = "LinkedIn"

[[params.handles]]
link = "https://twitter.com/mepgg"
name = "Twitter"

[[params.handles]]
link = "https://github.com/pgg1610"
name = "GitHub"

[[params.handles]]
link = "https://www.instagram.com/pgg1610/"
name = "Instagram"

#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"

#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
