---
date: "2021-07-03"
description: Example of how to implement a convolutional neural network in PyTorch
pubtype: Markdown post
featured: True
tags:
- Writing

title: Transition words and phrases R
---

Transition words/phrases are writing devices which help bridge ideas and guide the reader through the prose. When used strategically and _sparingly_ they connect multiple ideas and make the flow you'd have planned much more clearer to the reader. 

In my experience, I have made use of transition words even when delivering talks. They help add in necessary connections as you might glide through your slide deck and the information in the previous slide is not directly available to your audience. 

> “Music is the space between the notes” - Claude Debussy

**Connect and follow-on an idea**

$$
\begin{table}[]
\centering
\caption{Transformations Associated with the Johnson System}
\begin{tabular}{|l|l|l|l|}
\hline
Johnson Family & Transformation & Parameter Conditions & X Condition \\ \hline
S_B & Z=\gamma + \eta ln(\frac {X - \epsilon} {\lambda + \epsilon - X}) & \eta, \lambda >0, -\infty < \gamma, \epsilon < \infty & \epsilon < X < \epsilon + \lambda \\ \hline
S_L & Z=\gamma + \eta ln(X - \epsilon) & \eta >0, -\infty < \gamma, \epsilon < \infty & X > \epsilon \\ \hline
S_U & Z=\gamma + \eta \sinh^{-1}(\frac {X - \epsilon} {\lambda}) & \eta, \lambda >0, -\infty < \gamma, \epsilon < \infty & -\infty < X < \infty \\ \hline
\end{tabular}
\end{table}
$$

Furthermore | As an example | In fact | In addition to

Additionally | Likewise | For instance | Moreover

In turn

For example     	| As well as        	| Similarly       	|

Another reason  	| Along with        	| Whereas         	|

Again           	| Coupled with      	| Simply said/put 	|

Correspondinly  	| Speaking of       	|                 	|

Identically     	| Along those lines 	|                 	

**Words that show cause**

| Accordingly             	| Otherwise             	| As you can see       	|
| As a result             	| As is the case today  	| For all those reason 	|
| Because                 	| So then               	| Presumably           	|
| Consequently            	| Subsequently          	| This after all       	|
| Due to                  	| Therefore             	| Whereas              	|
| Hence                   	| This is why           	| Simply said/put      	|
| For this purpose/reason 	| Incidently            	| It stands to reason  	|
| Perhaps                 	| Following this        	| As was typical       	|

**Words that show contrast**

| Instead            	| Nevertheless 	| Although       	|
| On the other hand  	| In contrast  	| However        	|
| On the contrary    	| Whereas      	| Even though    	|
| Other than         	| Yet          	| Different from 	|
| Besides            	| Even though  	| That said      	|
| Otherwise          	| However      	| Nonetheless    	|
| Notwithstanding    	| Conversely   	| As opposed to  	|

**Words that add emphasis**


| Certainly               	| Certainly          	| In essence         	|
| No doubt (undoubtedly)  	| Of course          	| Unquestionably     	|
| Indomitably             	| Obviously          	| Especially         	|
| above aall              	| Particularly       	| For the most part  	|
| As a rule               	| In effect          	| Chiefly            	|
| It stands to reason     	| In this situation  	| Primarily          	|
| in fact                 	| indeed             	| surely             	|
| specifically            	| with this in mind  	| another key point  	|

**Summary**

| in brief            	| in short           	| wrapping up         	|
| to sum up           	| to conclude        	| circling back       	|
| in sum              	| in the end         	| given these points  	|
| all in all          	| by and large       	| ultimately          	|
| As a rule           	| In effect          	| Chiefly             	|

**Concessionary**

| That being true     	| to be sure         	| of course           	|
| Naturally           	| granted            	|                     	|
